spring.application.name=triage-backend

spring.config.import=optional:file:.env-secret-local[.properties]

openrouter.base-url=https://openrouter.ai/api/v1
openrouter.model=inclusionai/ring-2.6-1t:free
openrouter.timeout-ms=8000
openrouter.api-key=${OPENROUTER_API_KEY:}
